- name: Run ldapmockserver project
  hosts: all
  gather_facts: false
  remote_user: root
  become: true
  tasks:
    - name: Create target folder
      ansible.builtin.file:
        path: "/opt/ldapmockserver/"
        state: directory
        mode: '0755'
    - name: Copy users
      ansible.builtin.copy:
        src: ./users.ldif
        dest: /opt/ldapmockserver/users.ldif
        mode: '0644'

    - name: Copy JAR to the remote server
      copy:
        src: ./target/ldapmockserver-0.0.1-SNAPSHOT.jar
        dest: /opt/ldapmockserver/ldapmockserver-0.0.1-SNAPSHOT.jar
        mode: '0755'
        force: yes

    - name: Create a systemd service file for the JAR
      template:
        src: templates/ldapmockserver.service.j2
        dest: /etc/systemd/system/ldapmockserver.service
        mode: '0644'

    - name: Reload systemd to recognize the new service
      command: systemctl daemon-reload

    - name: Enable the service
      systemd:
        name: ldapmockserver
        enabled: yes
        state: started
